[X,Y,Z]=sphere(20);
figure(1);
surf(X,Y,Z);
shading interp;
hold on;
mesh(2*X,2*Y,2*Z);
colormap(hot);
hidden off;
axis equal;
axis off;
[X,Y,Z]=sphere(20);
figure(2);
index=find(X<0&Y<0&Z>0);
Z2=Z;
Z2(index)=NaN;
surf(X,Y,Z2);
axis equal;
axis off;
[X,Y,Z]=sphere(20);
index=find(Z>0);
Z3=Z;
Z3(index)=zeros(size(index));
figure(3);
surf(X,Y,Z3);
hidden off;
axis equal;
axis off;
[X,Y,Z]=sphere(20);
m=20;
z=1.2*(0:m)/m;
r=ones(size(z));
theta=(0:m)/m*2*pi;
x1=r'*cos(theta);
y1=r'*sin(theta);
z1=z'*ones(1,m+1);
x=(-m:2:m)/m;
x2=x'*ones(1,m+1);
y2=r'*cos(theta);
z2=r'*sin(theta);
figure(4);
surf(x1,y1,z1);
axis equal;
axis off;
hold on;
surf(x2,y2,z2);
axis equal;
axis off;